version: '3.5'

services:
  postgres:
    container_name: postgres-desafio
    image: postgres
    
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRESS_DB: desafio
    ports:
      - "5442:5432"
    volumes: 
      - ./data:/var/lib/postgresql/data
        # copy the sql script to create tables
      - ./sql/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
